import React from "react";
import ProfilePage from "../../components/Profile";
import Head from "next/head";

const Profile = () => {
  return (
    <>
      <Head>
        <title>Mern Social Media App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProfilePage />
    </>
  );
};

export default Profile;
