import React from "react";
import Head from "next/head";
import FriendsPage from "../components/Friends";

const Friends = () => {
  return (
    <>
      <Head>
        <title>Mern Social Media App | Friends</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FriendsPage />
    </>
  );
};

export default Friends;
